### ISSUE TITLE
Unify the low power domain and high power domain names across chips?

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-pacs#100]
Opening this to discuss the idea of unifying the terminology and naming convention of the low-power parts of the chips.

Prior to the C6, this was typically named `RTC` but it seems going forward this will now be called `LP`. Inversely, there was no prefix for HP in older chips but post C6 it now crops up sometimes.

Do we want to convert all names to either one or the other across all chips? There are already a few `cfg`'s working around the name differences in esp-hal.

## Idea 1 - Rename RTC to LP, strip HP

This means renaming RTC stuff to LP and stripping the occasional `HP` prefix, essentially, unless specified assuming it's HP.

## Idea 2 - Rename RTC to LP, prefix the rest with HP

Same as above but instead of stripping the HP prefix, add it to everything that isn't a LP related peripheral

## Idea 3 - Do nothing

Just work around the differences in esp-hal etc.

**Comment by jessebraham** [comment]
I've apprehensive to change the names of peripherals too much, as I've already put a fair bit of effort into aligning the peripheral names with how they're abbreviated in the TRMs. Would be kind of a shame for that effort all to be wasted.

I'm also not sure we should make any rash decisions based on the C6 alone, given that there are multiple new chips still coming out this year and we have no idea what surprises they will hold.

**Comment by jessebraham** [comment]
Just adding that this may well be part of a larger discussion, as now that we've added support for the C6 and H2 it's clear that there are a few peripherals with two or more different names. A couples examples of this are `RTC_CNTL` vs `LP_CLKRST`, or `DPORT` vs `SYSTEM`.

**Comment by jessebraham** [comment]
Since we've unified `DPORT`/`PCR`/`SYSTEM` at the HAL-level already, I'm going to assume we'll continue to alias the peripherals there instead of renaming them here. So, gonna close this for now. We can always revisit it in the future if needed.
