### ISSUE TITLE
Use these pacs in svd2rust regression CI

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-pacs#14]
Currently it's still testing the old esp32 pac: https://github.com/rust-embedded/svd2rust/blob/7264731e4796c3b39a302fae89eab36d33a5008d/ci/script.sh#L607

**Comment by jessebraham** [comment]
Small correction, they are testing the *SVD*, which just happens to live in the *PAC* :) For this reason this issue is sort of off-topic and I will close it.

However, I have opened a PR in `svd2rust` which uses the official SVDs, and additionally checks the C3/S2/S3.
