### ISSUE TITLE
Overly verbose register field names

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-pacs#174]
For example: https://docs.rs/esp32c6/latest/esp32c6/lp_io/pin2/type.W.html

All the register fields are prefixed with a redundant `lp_gpio2` which makes the PAC a bit annoying to read and use. This comes from the base SVD, though, so I'm not sure if this is something that can be easily fixed.

**Comment by jessebraham** [comment]
I've added a workaround in our SVD generator to handle these field names. They unfortunately are not super consistent, and don't use the same naming conventions that were expected, so needed to be handled as a special case.

I will leave this issue open until I have published a new SVD for the ESP32-C6 and updated it here.
