### ISSUE TITLE
Typo in LCD_CAM.lcd_user.lcd_reset field doc

### ISSUE THREAD

**Issue by Dominaezzz** [esp-rs/esp-pacs#179]
https://docs.rs/esp32s3/0.23.0/esp32s3/lcd_cam/lcd_user/type.W.html#method.lcd_reset
The doc for that says "Bit 28 - The value of command." which is incorrect.

The TRM says "LCD_CAM_LCD_RESET Reset LCD module. (WO)". [link](https://www.espressif.com/sites/default/files/documentation/esp32-s3_technical_reference_manual_en.pdf#camlcdctrl)

**Comment by jessebraham** [comment]
Thanks for this issue. I will do a quick review of the entire peripheral and try to spot any other obvious problems in the next couple days.
