### ISSUE TITLE
[esp32c3] SW_INTR_* Interrupt sources missing

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-pacs#19]
The following interrupt sources are missing for the esp32c3 interrupt controller.

- SW_INTR_0 = 50
- SW_INTR_1 = 51
- SW_INTR_2 = 52
- SW_INTR_3 = 53

These are not related to any hardware, which is possibly why they were missed.

**Comment by jessebraham** [comment]
You are correct, given that these are not tied to specific peripherals they were not included.

We can definitely add these to any old peripheral though; even though in the SVD the interrupts belong to peripherals, in the PAC no such relation exists and only a single Enum of interrupts is generated (see [here](https://docs.rs/esp32c3/latest/esp32c3/enum.Interrupt.html)). Should be simple to just patch these in, `INTERRUPT_CORE0` or `SYSTEM` might make most sense, but again it doesn't really matter.
