### ISSUE TITLE
`README.md` should mention when to use `common_patches` directory and discuss patching conventions

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-pacs#226]
Since we've now changed the workflow slightly, the `README.md` should be updated accordingly. It should be clear to users who have never contributed before how to write patches and where to place them.

Are the common patches common to *all* devices? What should users do in cases of exceptions? What if patches are common to only a couple devices, do they still belong in this directory? Are we differentiating these from patches which apply to all chips in any way?

cc @MabezDev @burrbull

**Comment by burrbull** [comment]
When https://github.com/rust-embedded/svdtools/pull/229 is merged you could see how entire patch YAML looks with all rules _include'd with:
```
svdtools expand-patch /path/to/yaml
```
