### ISSUE TITLE
TWAI is missing

### ISSUE THREAD

**Issue by maximeborges** [esp-rs/esp-pacs#28]
I've been looking for a while in the SVD and generated Rust code but can't find any trace if TWAI there.
Am I missing something or is it completely missing from the SVDs?

**Comment by jessebraham** [comment]
You are correct, they are indeed missing. For whatever reason this peripheral is not included in the peripheral description files I use to generate the SVDs. I will try to get ahold of these files and get updated SVDs out, however this will likely take some time.

**Comment by jessebraham** [comment]
That would be great, thank you for offering!

**Comment by maximeborges** [comment]
Implemented in #29, maybe we can keep this issue open until there is a proper implementation on your source files?
