### ISSUE TITLE
Create a PAC for the ESP32-P4

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-pacs#81]
I still haven't created an SVD for this chip yet, but once I do I'll get a PAC made up.

**Comment by felipebalbi** [comment]
> I started work on the SVD for this device earlier this week.

unrelated to your work, just generally curious. Are you writing the SVD by hand based on documentation alone? I'm assuming xtensa did not provide an SVD, then. Correct?

**Comment by jessebraham** [comment]
The SVD is probably ready for an initial release, however I still do not have hardware so there's not much rush. I will continue to refine the SVD in the meantime, and will likely have a PAC pushed within the next month or so.
